### Get all articles
GET http://localhost:1234/articles

### Get a specific article
GET http://localhost:1234/articles/4

### Get articles by date
GET http://localhost:1234/articles?createdAt=2023-04-04T15:00:00.000Z

### Create an article
POST http://localhost:1234/articles
Content-Type: application/json

{
    "name": "New Article",
    "barcode": "1234567890123",
    "exhibition": 3,
    "shelf": 20,
    "warehouse": 100
}

### Update an article
PUT http://localhost:1234/articles/4
Content-Type: application/json

{
    "name": "New Article",
    "barcode": "3434343434",
    "exhibition": 3,
    "shelf": 20,
    "warehouse": 123
}

### Delete an article
DELETE http://localhost:1234/articles/4
