### Get all articles
GET http://localhost:1234/articles

### Get a specific article
GET http://localhost:1234/articles/3b24435e-69e1-11ee-8fb5-a036bcd0d29a

### Get articles by date
GET http://localhost:1234/articles?createdAt=2023-09-21T17:04:42.000Z

### Create an article
POST http://localhost:1234/articles
Content-Type: application/json

{
    "userId": "439c041f-69c6-11ee-8fb5-a036bcd0d29a",
    "article": {
        "articleName": "New Article 121 21 22 1",
        "barcode": "1234567890123",
        "exhibition": 3,
        "shelf": 20,
        "warehouse": 100,
        "category": {
            "categoryName": "Tornillería"
        }
    }
}

### Update an article
PUT http://localhost:1234/articles/000069e6-6177-11ee-9823-a036bcd0d29a
Content-Type: application/json

{
    "articleName": "updated article 00121212",
    "barcode": "1234567890123",
    "exhibition": 3,
    "shelf": 20,
    "warehouse": 100,
    "category": {
        "categoryName": "Guantes"
    }
}

### Delete an article
DELETE http://localhost:1234/articles/a5bccc2c-69ea-11ee-8fb5-a036bcd0d29a

// specific for users

### Get articles by user id
GET http://localhost:1234/articles/user/a5c43a8e-69ea-11ee-8fb5-a036bcd0d29a
