### Get all articles
GET http://localhost:1234/articles

### Get a specific article
GET http://localhost:1234/articles/8a70c5a3-5a43-11ee-832e-a036bcd0d29a

### Get articles by date
GET http://localhost:1234/articles?createdAt=2023-09-21T17:04:42.000Z

### Create an article
POST http://localhost:1234/articles
Content-Type: application/json

{
    "userId": "44ac30b2-5faf-11ee-999d-a036bcd0d29a",
    "article": {
        "articleName": "New Article 121 21 22 1",
        "barcode": "1234567890123",
        "exhibition": 3,
        "shelf": 20,
        "warehouse": 100,
        "category": {
            "categoryName": "Tornillería"
        }
    }
}

### Update an article
PUT http://localhost:1234/articles/8a70c5a3-5a43-11ee-832e-a036bcd0d29a
Content-Type: application/json

{
    "articleName": "updated article 00121212",
    "barcode": "1234567890123",
    "exhibition": 3,
    "shelf": 20,
    "warehouse": 100,
    "category": {
        "categoryName": "Guantes"
    }
}

### Delete an article
DELETE http://localhost:1234/articles/1

// specific for users

### Get articles by user id
GET http://localhost:1234/articles/user/4af975d8-5faf-11ee-999d-a036bcd0d29a
