### Get all categories
GET http://localhost:1234/categories

### Get a specific article
GET http://localhost:1234/categories/a5bda104-69ea-11ee-8fb5-a036bcd0d29a

### Create an article
POST http://localhost:1234/categories
Content-Type: application/json

{
    "categoryName": "Cordelería"
}

### Update an article
PUT http://localhost:1234/categories/d352a2af-5876-11ee-87d4-a036bcd0d29a
Content-Type: application/json

{
    "categoryName": "Tornillería"
}

### Delete an article
DELETE http://localhost:1234/categories/a5bda104-69ea-11ee-8fb5-a036bcd0d29a
